mysql -uroot <.\table_fl.sql
mysql -uroot <.\data0.sql
mysql -uroot <.\data1.sql
mysql -uroot <.\data2.sql
mysql -uroot <.\data3.sql
mysql -uroot <.\data4.sql
mysql -uroot <.\data5.sql
mysql -uroot <.\data6.sql
mysql -uroot <.\data7.sql
mysql -uroot <.\data8.sql
mysql -uroot <.\data9.sql
mysql -uroot <.\data10.sql
mysql -uroot <.\data11.sql
mysql -uroot <.\data12.sql
mysql -uroot <.\data13.sql
mysql -uroot <.\data14.sql
mysql -uroot <.\data15.sql
mysql -uroot <.\data16.sql
mysql -uroot <.\data17.sql
mysql -uroot <.\data18.sql
mysql -uroot <.\data19.sql
mysql -uroot <.\data20.sql
mysql -uroot <.\data21.sql
mysql -uroot <.\data22.sql
mysql -uroot <.\data23.sql
mysql -uroot <.\data24.sql
mysql -uroot <.\data25.sql
mysql -uroot <.\data26.sql
mysql -uroot <.\data27.sql
mysql -uroot <.\data28.sql
mysql -uroot <.\data29.sql
mysql -uroot <.\data30.sql
mysql -uroot <.\data31.sql
mysql -uroot <.\data32.sql
mysql -uroot <.\data33.sql
mysql -uroot <.\data34.sql
mysql -uroot <.\data35.sql
mysql -uroot <.\data36.sql
mysql -uroot <.\data37.sql
mysql -uroot <.\data38.sql
mysql -uroot <.\data39.sql
mysql -uroot <.\data40.sql
mysql -uroot <.\data41.sql
mysql -uroot <.\data42.sql
mysql -uroot <.\data43.sql
mysql -uroot <.\data44.sql
mysql -uroot <.\data45.sql
mysql -uroot <.\data46.sql
mysql -uroot <.\data47.sql
mysql -uroot <.\data48.sql
mysql -uroot <.\data49.sql
mysql -uroot <.\data50.sql
mysql -uroot <.\data51.sql
mysql -uroot <.\data52.sql
mysql -uroot <.\data53.sql
mysql -uroot <.\data54.sql
mysql -uroot <.\data55.sql
mysql -uroot <.\data56.sql
mysql -uroot <.\data57.sql
mysql -uroot <.\data58.sql
mysql -uroot <.\data59.sql
mysql -uroot <.\data60.sql
mysql -uroot <.\data61.sql
mysql -uroot <.\data62.sql
mysql -uroot <.\data63.sql
mysql -uroot <.\data64.sql
